import React, { useState, useEffect } from 'react';
import styled from 'styled-components';
import { MainLayout } from '../layouts/MainLayout';
import InstructionsTable from '../components/InstructionsTable';
import { API_ENDPOINTS } from '../constants/api';
import axios from 'axios';
import { useToast } from '../services/ToastService';
import LoadingOnPage from '../components/shared/LoadingOnPage';
import { useNavigation } from '../hooks/useNavigation';
import { useAuth } from '../contexts/AuthContext';

const InvoicesPage = () => {
    const [currentPage, setCurrentPage] = useState(1);
    const [totalPages, setTotalPages] = useState(1);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);
    const [filteredData, setFilteredData] = useState([]);
    const [filters, setFilters] = useState({
        is_paid: '',
        per_page: 10,
        page: 1
    });
    const { showError } = useToast();
    const navigation = useNavigation();
    const { user } = useAuth();

    const columns = [
        { key: 'wpr', header: 'WPR no.', width: 'wpr' },
        { key: 'title', header: 'Title', width: 'title' },
        { key: 'price', header: 'Price', width: 'price' },
        { key: 'is_paid', header: 'Status', width: 'is_paid' },
        { key: 'paid_at', header: 'Paid at', width: 'paid_at' }
    ];

    const fetchInvoices = async () => {
        try {
            setLoading(true);
            
            const token = localStorage.getItem('token');
            if (!token) {
                throw new Error('No authentication token found');
            }

            // Build query parameters
            const queryParams = new URLSearchParams();
            if (filters.is_paid !== '') queryParams.append('is_paid', filters.is_paid);
            queryParams.append('per_page', filters.per_page.toString());
            queryParams.append('page', currentPage.toString());
            
            const response = await axios.get(`${API_ENDPOINTS.INVOICES}?${queryParams}`, {
                headers: {
                    'Authorization': `Bearer ${token}`,
                    'Content-Type': 'application/json',
                    'Accept': 'application/json'
                }
            });

            if (response.data?.data) {
                setFilteredData(response.data.data);
                setTotalPages(Math.ceil(response.data.total / filters.per_page));
            } else {
                setFilteredData([]);
            }
        } catch (error) {
            console.error('Error fetching invoices:', error);
            setError(error.message || 'Failed to fetch invoices');
            showError(error.message || 'Failed to fetch invoices');
            setFilteredData([]);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchInvoices();
    }, [currentPage, filters]);

    const handleFilterChange = (filterId) => {
        setFilters(prev => ({
            ...prev,
            is_paid: filterId === 'paid' ? '1' : filterId === 'unpaid' ? '0' : '',
            page: 1
        }));
        setCurrentPage(1);
    };

    const handlePageChange = (page) => {
        setCurrentPage(page);
    };

    const renderCell = (key, value) => {
        if (key === 'is_paid') {
            return value ? 'Paid' : 'Unpaid';
        }
        if (key === 'price') {
            return `£${parseFloat(value).toFixed(2)}`;
        }
        if (key === 'paid_at') {
            return value ? new Date(value).toLocaleDateString('en-GB') : '-';
        }
        return value;
    };

    const handleRowClick = (rowData) => {
        if (typeof navigation.handleNavigationFromTableRow === 'function') {
            navigation.handleNavigationFromTableRow(rowData)
        };
    }

    return (
        <MainLayout 
            isInvoicePage={true}
            title="Invoices"
            filterButtons={[
                { id: '', label: 'All', dotColor: 'white' },
                { id: 'paid', label: 'Paid', dotColor: 'success' },
                { id: 'unpaid', label: 'Unpaid', dotColor: 'warning' }
            ]}
            onFilterChange={handleFilterChange}
        >
            {loading && <LoadingOnPage />}
            <DashboardContainer>
                <MainContent>
                    <TableContainer>
                        <InstructionsTable 
                            data={filteredData}
                            title="All Invoices"
                            subtitle={`Monthly invoices generated by ${user?.type === 'firm' ? 'firm' : 'individual'}`}
                            columns={columns}
                            renderCell={renderCell}
                            minHeight={495}
                            noDataCellHeight={420}
                            itemsPerPage={filters.per_page}
                            currentPage={currentPage}
                            totalPages={totalPages}
                            onPageChange={handlePageChange}
                            loading={loading}
                            error={error}
                            onRowClick={handleRowClick}
                        />
                    </TableContainer>
                </MainContent>
            </DashboardContainer>
        </MainLayout>
    );
};

const DashboardContainer = styled.div`
  width: 100%;
  max-width: 1728px;
  margin: 0 auto;
  box-sizing: border-box;
`;

const MainContent = styled.div`
  display: flex;
  flex-direction: column;
  width: 100%;

  @media (min-width: 1280px) {
    flex-direction: row;
  }
  
  @media (max-width: 1280px) {
    gap: 24px;
  }
`;

const TableContainer = styled.div`
  background-color: white;
  border-radius: 12px;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
  overflow: hidden;
  width: 100%;
`;

export default InvoicesPage;
